### ISSUE TITLE
Unable to drag and drop the widget

### ISSUE THREAD

**Issue by santhosh82** [rajeshvaya/angular-material-widget-engine#5]
Hi,
First of all, this is an awesome library. I implemented the widget engine library but I am unable to drag and drop the widgets. When I tried to debug, I am getting **event._initiatedByDragger** as **undefined** in the function  **$element.on('dragstart', function(event)**

But I passed through this line  **event._initiatedByDragger = true;** in  **mdWidgetEngineWidgetTileDragger** function. I am not sure where and why this is happening.
(I am trying to compare the degub between my JS file and the JS file from your github example.)
Any help would be greatly appreciated. Please let me know if you need more info.

**Comment by rajeshvaya** [comment]
@santhosh82 thanks!

The dragging of widget is controlled purely by the config set while initializing the widget engine. There is a `sticky` property when set to true will make the widget un-draggable (so make sure you are setting the `sticky` property to `false`).

e.g.

```JSON
{
            "name": "column1",
            "background": "#e9ebee",
            "size": 55,
            "widgets":[
                {
                    "name": "report_1", 
                    "title": "Report One", 
                    "type": "include", 
                    "content": "/example/data/widgets/report_1.html", 
                    "refresh": 10, 
                    "resize": true, 
                    "minHeight": "auto", 
                    "maxHeight": "auto",
                    "sticky": false,
                    "stickyControl": true
                },
                {"name": "report_2", "title": "Report Two", "type": "include", "content": "/example/data/widgets/report_1.html", "refresh": 10, "resize": true, "minHeight": "auto", "maxHeight": "auto"}
            ]
}
``` 


Also, you can try to see more examples under the [gh-pages](https://github.com/rajeshvaya/angular-material-widget-engine/tree/gh-pages) branch. That branch points to [this](https://rajeshvaya.github.io/angular-material-widget-engine/)

The 2 demo solutions are [here](https://rajeshvaya.github.io/angular-material-widget-engine/demo/simple_dashboard/) and [here](https://rajeshvaya.github.io/angular-material-widget-engine/demo/multiple_columns/)

**Comment by santhosh82** [comment]
I had checked my config file and the sticky property is set to false. When I drag a widget, the event object in the **$element.on('dragstart', function(event)** is having both the  **initiatedByDragger** and the **dataTransfer** to undefined. Instead the **initiatedByDragger** attribute needs to be True. I am not sure why and where this happening.
![widgetengineerror](https://user-images.githubusercontent.com/10835847/28259693-bef6a44a-6a94-11e7-8679-9db2e2eae3f2.png)

In the above picture you can see in the console, the attributes are undefined (I am getting assigned **event._initiatedByDragger = true;** in the lines above)
Thanks for the immediate replies.

**Comment by santhosh82** [comment]
Finally, I found the solution. Removing jQuery solves the problem(the drag events are now handled by angularjs) and the drag and drop functionality is working fine but I need jQuery for other files. How do I need to get around this new problem?

**Comment by rajeshvaya** [comment]
@santhosh82 thats great, Although using jQuery with Angular is not recommended, but if needed, you can isolate the scope jQuery object or you can use something of kind [mentioned here](https://stackoverflow.com/questions/23900291/prevent-angularjs-from-using-jquery-library)

**Comment by santhosh82** [comment]
Thanks for the link. That helped me. Yay.
